### ISSUE TITLE
FR: today queries in columns

### ISSUE THREAD

**Issue by yoyurec** [yoyurec/logseq-awesome-content#1]
...

**Comment by yoyurec** [comment]
done

**Comment by Gitbreast** [comment]
@yoyurec Little question. How to write a today queries like this?
![](https://github.com//yoyurec/logseq-awesome-content/raw/main/screenshots/today-queries.png)

How it works? Does it need to be typed or pasted manually in new journal of everyday? I couldn't find any info of it in awesome-ui issues.

**Comment by yoyurec** [comment]
in Logseq already some simple queries like "deadline" block.
but for same as on image you should compose an advanced query, then insert it to `config.edn` and it will appear in today's journal automatically.

 to tricky for beginner... ((
 
_PS: in case you don't want to spend your time -I've already spent mine - **"Starter pack" for Logseq** has this setup already + more things, check details  https://www.buymeacoffee.com/yoyurec/extras_
