### ISSUE TITLE
Mobile version do not work for horizontal screen

### ISSUE THREAD

**Issue by ThreeIce** [yoyurec/logseq-awesome-content#3]
**Info:**
- OS: ipad os
- Logseq ver: 0.8.18
- Plugin ver: automatically load by css link
- Theme name: Awesome Content

- [ ] ⚠ Do i have issue with DISABLED my `custom.css`?

**Description:**
A clear and concise description of what the bug is......

**To Reproduce:**
 ...

**Expected behavior:**
 ...

**Screenshots**
![29EB46C8-543F-43FD-BC5D-98C977B013B0](https://user-images.githubusercontent.com/46413648/224055522-23a6d978-29eb-487c-83ca-97d1a1df4920.jpeg)
![3CF632AE-32FD-44B3-9AD2-8AFA6BE2B22E](https://user-images.githubusercontent.com/46413648/224055591-866a2346-de24-4243-b49e-0f8316c193cc.jpeg)

**Attach files**
Add (via drag-n-drop) .zip with `.md` files (if it needs) to help with bugfixind

**Comment by yoyurec** [comment]
what are your device sizes?

`@import url("https://raw.githack.com/yoyurec/logseq-awesome-content/main/src/awesomeContent-cdn.css") only screen and (max-width: 1024px);` <--- try to set bigger `max-width`

**Comment by ThreeIce** [comment]
My device sizes are 2360 x 1640.
I set it to 2400 and 3000. It doesn’t work.

**Comment by yoyurec** [comment]
what about delete at all? only imports stays : `@import url("https://raw.githack.com/yoyurec/logseq-awesome-content/main/src/awesomeContent-cdn.css");`

**Comment by yoyurec** [comment]
btw, custom.css can be cached, so maybe also need to reindex

**Comment by ThreeIce** [comment]
I have tried. I even restart the whole app.

**Comment by ThreeIce** [comment]
other custom css works well
![5B5462EE-3AB8-453D-812F-3FA062657325](https://user-images.githubusercontent.com/46413648/224068293-74d49488-94ca-4ab4-b7dc-09e29bcda38a.png)

**Comment by yoyurec** [comment]
oh! i've found )
awesomeContent-cdn.css is a collection of modules imports. WITH max-width

**Comment by yoyurec** [comment]
i've pushed update, but file still chached in cloud
so you can use for now:
```
@import url("https://raw.githack.com/yoyurec/logseq-awesome-content/main/src/modules/admonition/admonition.css");
@import url("https://raw.githack.com/yoyurec/logseq-awesome-content/main/src/modules/calculator/calculator.css");
@import url("https://raw.githack.com/yoyurec/logseq-awesome-content/main/src/modules/columns/columns.css");
@import url("https://raw.githack.com/yoyurec/logseq-awesome-content/main/src/modules/flashcards/flashcardAwesome.css");
@import url("https://raw.githack.com/yoyurec/logseq-awesome-content/main/src/modules/headersLabels/headersLabels.css");
@import url("https://raw.githack.com/yoyurec/logseq-awesome-content/main/src/modules/mermaid/mermaid.css");
@import url("https://raw.githack.com/yoyurec/logseq-awesome-content/main/src/modules/quotes/quotes.css");
@import url("https://raw.githack.com/yoyurec/logseq-awesome-content/main/src/modules/tasks/tasks.css");
@import url("https://raw.githack.com/yoyurec/logseq-awesome-content/main/src/modules/code/code.css");
@import url("https://raw.githack.com/yoyurec/logseq-awesome-content/main/src/modules/other/other.css");
```

**Comment by yoyurec** [comment]
cdn updated, `@import url("https://raw.githack.com/yoyurec/logseq-awesome-content/main/src/awesomeContent-cdn.css");` should work
