### ISSUE TITLE
How to use the admonition blocks?

### ISSUE THREAD

**Issue by sbwcwso** [yoyurec/logseq-awesome-content#4]
like this:
![image](https://user-images.githubusercontent.com/48000576/224877166-f578fde3-6892-469c-b1a5-f8706eac543c.png)

**Comment by yoyurec** [comment]
it's not plugin feature, it's default (just restyled)
check Logseq docs https://docs.logseq.com/#/page/640a4667-5a7f-41cb-9d6a-bb858b356175
use ~"/"~ `<` command

**Comment by sbwcwso** [comment]
> it's not plugin feature, it's default (just restyled) check Logseq docs https://docs.logseq.com/#/page/640a4667-5a7f-41cb-9d6a-bb858b356175 use `/` command

Thank you very much. I just have to use the `<` command in org mode.

**Comment by yoyurec** [comment]
hm.. just checked - `<` command ))

**Comment by AnweshGangula** [comment]
its not clear how to use Admonitions - I can't find documentation in logseq docs either.
___
Just found that it can be added by using `<` command _(similar to the `/` command)_ which will show you a list of possible type of admonitions
